### ISSUE TITLE
Huge Files

### ISSUE THREAD

**Issue by ralphgoebel** [Microsoft/Intune-Win32-App-Packaging-Tool#1]
Hi,

I have an issue using the tool. I have converted a 7ZIP installation package. The source file has a size of 1.4 MB, but the resulting .intunewin has a size of about 3.4GB. What happens here? What can I do?

Thanks and regards

Ralph

**Comment by schenardie** [comment]
Hi Ralph, i had the same problem until i realized that the tools it compressing everything which is under the Setup Folder (-c option)

try to create a new folder with only 7zip installer and try to run that again..

**Comment by ralphgoebel** [comment]
Wow, thanks for fast help, that was the reason :)
Unfortunately, I am not a developer, so I cannot fix it :(

**Comment by dsghi** [comment]
This is clearly a bug, I was ending up with a 6GB intunewin file from a 1MB exe.. this is not called out in the documentation here nor on docs.microsoft.com. You should re-open this issue so it can be tracked and fixed.

**Comment by schenardie** [comment]
just re-read the documentation mate. I made the same mistake but it clearly says

-c <setup_folder> Setup folder for all setup files. All files in this folder will be compressed into .intunewin file.
**Only the setup files for this app should be in this folder.**

**Comment by dsghi** [comment]
LOL, OK, then consider this a feature request, because that's ridiculous... what's the point of specifying the application if it's going to just grab the whole directly?

I've been working with MS support for a week because an application won't install, and it turns out it's because it uploaded OK but is ultimately crashing on the agent download with some obscure web service error.. After I repackaged it works.

**Comment by schenardie** [comment]
Because you can call a powershell script which deploy more than one .exe or .msi. Thats why it wraps all the folder.  Lets say you have a exe which needs a separate .config to be deployed. You create the folder with the 3 files inside (EXE, CONFIG and PS1) and call the ps1 to install the app and copy the config file after.

**Comment by dsghi** [comment]
Thanks for the clarification.. I don't see it explained quite as eloquently where I got my information: https://docs.microsoft.com/en-us/intune/apps-win32-app-management

**Comment by schenardie** [comment]
Agree with you that the documentation could be better..  Maybe once they move to Production it will get updated with all the capabilities and better examples.
